# Generated by Django 3.1.3 on 2020-11-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestcrickter',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_crickter', to='trivia_app.person'),
        ),
        migrations.AlterField(
            model_name='bestcrickter',
            name='player_name',
            field=models.CharField(blank=True, default='vote', max_length=50, null=True),
        ),
    ]
