# Generated by Django 3.1.3 on 2020-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0002_auto_20201123_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestcrickter',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_crickter', to='trivia_app.person'),
        ),
    ]
