# Generated by Django 3.1.3 on 2020-11-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0003_auto_20201123_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='indianflagcolor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_flag_color', to='trivia_app.person'),
        ),
        migrations.AlterField(
            model_name='bestcrickter',
            name='player_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indianflagcolor',
            name='flag_color',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
